### ISSUE TITLE
目录栏（Table of Contents）显示的吐槽

### ISSUE THREAD

**Issue by heshengpku** [chendy560/c2d#4]
![图片](https://user-images.githubusercontent.com/19176890/54744899-23c16300-4c03-11e9-8a74-24aad9f960a5.png)

我很好奇这个名称再长一些会不会出问题。

另外在4.3.后面换行有点不好看，后面对象结构的1.16也是。

**Comment by chendy560** [comment]
这是asciidoctor最终生成html的效果，默认的css就是这样的，其实并不在这个项目的讨论范围内啦
